### ISSUE TITLE
Haskell-Projekt erzeugen

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#1]

**Comment by jan-christiansen** [comment]
- Bitte gib bei den `build-depends` irgendeine Einschränkung der Version von `haskell-src-exts` an. Momentan wird die Bibliothek immer mit der aktuellsten Version gebaut, das kann später natürlich schnell zu Fehlern führen.
- Du hast in der Paket-Konfiguration sowohl eine `library` als auch ein `executable` konfiguriert. Es ist sinnvoller, nur eins von beidem zu definieren.
- Ich würde dir raten, deine Anwendung mit Hilfe der REPL zu testen. Du kannst zum Beispiel in dem Verzeichnis mit dem Sourcecode den Aufruf `cabal repl` nutzen, um eine REPL zu erhalten, die dein `Main`-Modul lädt. Auf diese Weise kannst du schnell Implementierungen testen.

**Comment by beje8442** [comment]
- haskell-src-exts ist auf aktuelle Version eingeschränkt.

- Paket bildet jetzt nur noch ein executable.

- Anwendung kann jetzt mit der REPL getestet werden.
