### ISSUE TITLE
Code-Verbesserungen

### ISSUE THREAD

**Issue by jan-christiansen** [beje8442/haskellToCoqCompiler#15]
Beim nächsten Treffen sollten wir einmal das Modul durchgehen und ich mache ein paar Vorschläge zur Verbesserung des Codes.

**Comment by beje8442** [comment]
-  Zeile auf c.a. 100 Zeichen Breite beschränken
-  Hilfsfunktionen in ein anderes Modul auslagern
-  Obsolete Hilfsfunktionen entfernen 
-  Funktionen wie 'isNoTypeSignature' durch Funktionskomposition oder Lambda Ausdrücke abbilden
-  'partition' verwenden um Liste mit Filterbedingung zu teilen
- Funktionen wie 'convertToArrowTerm' mit 'foldr' definieren
- 'mappend' mit (++) austauschen
- In 'TypeSignature' Datentype die Typsignaturen als Baumstruktur speichern
- Funktionen wie 'convertPatsAndTypeSigsToBinders' mit 'zipWith' umsetzen
- Fehlermeldungen genauer definieren

**Comment by jan-christiansen** [comment]
* rename `listToNonemptyList` to `singleton`

**Comment by jan-christiansen** [comment]
Magst du dieses Ticket bitte weiterschieben, falls du mit der Umsetzung fertig bist.

**Comment by jan-christiansen** [comment]
Bitte passe die Fehlermeldungen so an, dass sie das Argument ausgeben, dass sie nicht verarbeiten können. Wenn eine Funktion zum Beispiel ein bestimmtes Pattern nicht verarbeiten kann, sollte die Funktion in der Fehlermeldung dieses Pattern mit ausgeben.
