### ISSUE TITLE
Append Funktion in Coq braucht auch den Typ

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#16]

**Comment by jan-christiansen** [comment]
Ich verstehe dieses Ticket leider nicht. Was war die Aufgabe, die im Zuge dieses Tickets erledigt werden sollte?

**Comment by beje8442** [comment]
Die Funktion `append` wurde in Coq wie folgt übersetzt:
`Fixpoint append (xs ys : List a) :=
    match xs with
    | Nil => ys
    | Cons z zs => Cons z (append zs ys)
    end.`
Um die Funktion zu kompilieren muss noch die variable a bekannt gemacht werden:
`Fixpoint append (a : Type) (xs ys : List a) :=`
In der konkreten Anwendung wird der Typ inferriert.
