### ISSUE TITLE
Suche nach Funktionsweise von "arguments" Anweisung in Coq

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#17]

**Comment by beje8442** [comment]
Wie [hier](http://adam.chlipala.net/cpdt/html/InductiveTypes.html) nachzulesen ist reicht es in den meisten Fällen die Anweisung `Set Implicit Arguments` oben ins Modul zu schreiben.
Lediglich für Konstruktoren von Datentypen, die kein Argument (außer den Typen) nehmen muss extra die `Arguments` Anweisung verwendet werden.
Beispiel für den Listen Datentyp:
`Inductive List (a: Type) : Type :=
       | Nil : List a
       | Cons : a -> List a -> List a.`
`Arguments Nil [a].`

**Comment by jan-christiansen** [comment]
- Bitte den entsprechenden Absatz hier kurz zitieren.
- Was bedeutet das `[a]` in dem Beispiel?

**Comment by jan-christiansen** [comment]
> here the list of possibly_bracketed_ident is a prefix of the list of arguments of qualid where the ones to be declared implicit are surrounded by square brackets and the ones to be declared as maximally inserted implicits are surrounded by curly braces.

Bitte alle Argumente als "maximally inserted" definieren.

**Comment by jan-christiansen** [comment]
Ich glaube, dass du auch beim `Set Implicit Arguments` einmal sagen muss, dass die Argumente "maximally inserted" sind.
