### ISSUE TITLE
Datentypen und Funktionstypen mit arguments Anweisung erweitern

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#18]

**Comment by jan-christiansen** [comment]
Wie sehen die Anweisungen aus, die hinzugefügt werden?

**Comment by beje8442** [comment]
Für jeden polymorphen Datentyp, der einen Konstruktor hat der kein Argument nimmt, wie `Nil` im `List` Datentyp wird die `Arguments` Anweisung hinzugefügt z.B :  
`Arguments Nil [a]` (wenn der Typ mit 'a' deklariert ist).
