### ISSUE TITLE
Dateien einlesen und in AST parsen

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#2]

**Comment by jan-christiansen** [comment]
Am besten schreibst du die Implementierung so um, dass du sie per REPL nutzen kannst. Das heißt, du benötigst einfach einfach Funktion, die eine Datei einliest, parst und auf der Konsole ausgibt.

**Comment by beje8442** [comment]
Einfache Funktion 'parseFile' wurde in 'Main.hs' hinzugefügt und kann mit Hilfe der REPL getestet werden.
