### ISSUE TITLE
Monadische Transformation von einfachen Funktionen

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#20]
Einfache Funktionen ('plus' und 'not') monadisch nach Coq transformieren.

**Comment by jan-christiansen** [comment]
Die Argumente `a` und `b` in der folgenden Definition sollten einen Prefix erhalten, um sie von den Argumenten der Lambda-Funktionen zu unterscheiden.

```coq
Definition plus (a : option nat)
  (b : option nat)
   : option nat :=
  a >>=
  (fun a =>
     b >>=
     (fun b => return_ (a + b)))
```

Bitte nenne die beiden Argumente `oa` und `ob` und definiere den Prefix so, dass man ihn später einfach ändern kann.

**Comment by beje8442** [comment]
Argumente erhalten nun Prefix, den man durch Austausch einer Funktion verändern kann:
```
Definition plus (oa : option nat) 
   (ob : option nat)
     : option nat :=
  oa >>=
  (fun a =>
     ob >>=
     (fun b => return_ (a + b))).
```
