### ISSUE TITLE
Monadische Transformation von Datentypen

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#22]
Datentypen, die Argumente nehmen (`List a`) müssen monadisch transformiert werden

**Comment by jan-christiansen** [comment]
So wie alle Argumente einer Funktion monadisch werden, müssen auch _alle_ Argumente eines Datentyps monadisch werden. Zum Beispiel müssten die Argumente des folgenden Datentyps

`data Test = T1 Int | T2 String`

auch transformiert werden. Statt

```
Inductive Test : Type
  := T1 : nat -> Test
  |  T2 : String -> Test.

```

würde man also

```
Inductive Test : Type
  := T1 : option nat -> Test
  |  T2 : option String -> Test.
```

erwarten.

**Comment by beje8442** [comment]
Alle Argumente von Datentypen werden nun monadisch transformiert
