### ISSUE TITLE
Monadische Transformation von rekursiven Funktionen 

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#23]
Beispiel: append Funktion soll monadisch nach coq übersetzt werden

Im Kapitel ["Nested Inductive Types"](http://adam.chlipala.net/cpdt/html/Cpdt.InductiveTypes.html) steht mehr zu der Thematik

Rekursive Funktionen sollen auf 2 Arten transformiert werden können:
- mit einer Hilfsfunktion
- mit einem 'fuel' Argument

**Comment by beje8442** [comment]
Transformation mit einem 'fuel' Argument wurde umgesetzt. 
Die 'append' Funktion übersetzt nach : 

```
Fixpoint append (a : Type) (oxs
                 : option (List a)) (oys
                 : option (List a)) (fuel : nat) := 
              oxs >>=
              (fun (xs : List a) =>
                 oys >>=
                 (fun (ys : List a) =>
                    return_ (match xs with
                             | Nil => ys
                             | Cons z zs =>
                                 match fuel with
                                 | O => xs
                                 | S rFuel =>
                                     Cons z (append zs oys rFuel)
                                 end
                             end))).
```

**Comment by jan-christiansen** [comment]
Die aktuelle Transformation ist so leider nicht richtig.

Diese Ticket wird durch #29 geblockt.

**Comment by beje8442** [comment]
Dieses Ticket wurde in die Tickets #33 und #32 aufgeteilt
