### ISSUE TITLE
Linter verwenden

### ISSUE THREAD

**Issue by jan-christiansen** [beje8442/haskellToCoqCompiler#25]
Der Linter `hlint` gibt Vorschläge, wie man Haskell-Code verbessern kann.

https://github.com/ndmitchell/hlint#readme

Installiere den Linter und wende die Vorschläge auf den Code an. Am einfachsten ist die Installation über `cabal install hlint`.

**Comment by jan-christiansen** [comment]
- Ich erhalte beim Aufruf `hlint Coq/Converter.hs` einen Parserfehler. Tritt das bei dir auch auf? Falls nicht, welche Version von `hlint` verwendest du?
- Für die Module `Main`, `Monad` und `Util` werden noch Verbesserungsvorschläge aufgeführt.

**Comment by beje8442** [comment]
- Beim Aufruf von `hlint Coq/Converter.hs` tritt nun kein Parserfehler mehr auf.
- In den Modulen `Main`, `Monad` und `Util` werden nun keine hints mehr angezeigt.
