### ISSUE TITLE
Modulstruktur verbessern

### ISSUE THREAD

**Issue by jan-christiansen** [beje8442/haskellToCoqCompiler#28]
- Das Modul `HelperFunctions` sollte in mehrere Module zerlegt werden.
- Die kopierten Module sollte am besten in einem anderen Submodul liegen als die selbst erstellten Module.
- Bevor die Struktur verändert wird, sollte das Konzept auf dem Zettel besprochen werden.

**Comment by jan-christiansen** [comment]
Ich würde vorschlagen, dass du die kopierten Modul unter der Hierarchie `Language.Coq` einordnest.

**Comment by beje8442** [comment]
Man könnte die Stringkonvertierung von dem Coq-Ast in ein eigenes Modul auslagern.
