### ISSUE TITLE
Einige Rekursive Funktionen händisch in Coq übersetzen (mit fuel Argument)

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#29]
- append 
- reverse

**Comment by beje8442** [comment]
`TestDefinitions.v` wird jetzt in Coq (Version 8.8.1) kompiliert

**Comment by jan-christiansen** [comment]
Die Funktionen sollten am besten das Fuel zuerst betrachten und direkt `None` liefern, falls das Fuel aufgebraucht ist. Das ist die einfachere Implementierung.
