### ISSUE TITLE
Allgemeine Form von 'Fuel'-Funktionen herleiten

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#31]

**Comment by beje8442** [comment]
Allgemeine Form von 'Fuel'-Funktionen: 
- Fuel-Argument als erstes Argument in der Funktion einfügen.
- Fuel-Argument muss reduzierbar sein (bei der Umsetzung wird ein Integer verwendet).
- Alle Argumente und der Rückgabewert der Funktion (abgesehen vom Fuel-Argument) müssen monadisch gemacht werden. 
- Pattern Matching auf dem Fuel-Argument durchführen: 
   - Im Fall, dass es aufgebraucht ist wird ein Fehler zurückgegeben (Bei der `option` Monade wird `None` geliefert.
   - Im Fall, dass es nicht aufgebraucht ist wird die Funktionsdefinition eingefügt.
- Vor der Funktionsdefinition müssen alle Monadischen Parameter mit einem Bind-Operator versehen werden. 
- Jeder Fall des Pattern-Matchings muss einen monadischen Wert zurückliefern (ggf. `return_ `einfügen).
- Im rekursiven Funktionsaufruf muss das reduzierte Fuel-Argument übergeben werden. 
- Wenn andere rekursive Funktionen aufgerufen werden muss auch ein Fuel-Argument übergeben werden.

**Comment by jan-christiansen** [comment]
Was passiert mit nicht-rekursiven Funktionen, die eine rekursive Funktion aufrufen? Erhält die nicht-rekursive Funktion auch ein Fuel-Argument?

**Comment by beje8442** [comment]
Momentan erhält jede aufgerufene Funktion in einer rekursiv definierten Funktion ein Fuel-Argument.
Nicht-rekursive Funktionen sollten aber kein Fuel-Argument erhalten.

**Comment by beje8442** [comment]
Nicht-rekursive Funktionen, die eine rekursive Funktion aufrufen erhalten jetzt auch ein Fuel-Argument und geben es weiter (Beispiel `indexLength` in `test.hs`)
