### ISSUE TITLE
Rekursive Funktionen mit Hilfsfunktion transformieren

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#32]
Rekursive Funktionen sollen in 2 Funktionen geteilt werden, damit das abzubauende Element von Coq erkannt wird. 
Beispiel für Append: 
```
Fixpoint append' (a : Type) (xs : List a) (oys : option (List a)) : option (List a) :=
  match xs with
  | Nil => oys
  | Cons z ozs => return_ (Cons z (ozs >>= (fun zs => append' zs oys)))
  end.

Definition append (a : Type) (oxs oys : option (List a)) : option (List a) :=
  oxs >>= fun xs => append' xs oys.
```

**Comment by beje8442** [comment]
Rekursive Funktionen können jetzt mit Hilfsfunktion übersetzt werden. 
Hilfsfunktion ist `Definition` die monadische Signatur hat und den rekursiven Teil bindet. 
Rekursiver Teil hat nicht-monadischen Parameter (Argument auf dem Pattern-Matching durchgeführt wird) damit Coq erkennt, dass es das decreasing argument ist.

**Comment by jan-christiansen** [comment]
Die Transformation sollte in einigen Fällen anders arbeiten. Statt des Codes

```
return_ (match b with
              | false => true
              | true => false
              end)
```

sollte zum Beispiel der folgende Code erzeugt werden.

```
match b with
  | false => return_ true
  | true => return_ false
end
```

**Comment by beje8442** [comment]
`return_ `wird jetzt immer explizit vor den Rückgabewert gesetzt, außer der Rückgabewert ist schon monadisch.
