### ISSUE TITLE
Explizite Importe

### ISSUE THREAD

**Issue by jan-christiansen** [beje8442/haskellToCoqCompiler#34]
Die Importe sollten explizit die Funktionen und Datentypen auflisten, die importiert werden, um den Code verständlicher zu gestalten. Also zum Beispiel statt

`import Compiler.Types`

`import Compiler.Types (function1, function2, Type(..))`

**Comment by beje8442** [comment]
Folgende Module haben vollständig explizite Importe: 
- Types.hs
- NonEmptyList.hs
