### ISSUE TITLE
Verbesserung der Code-Formatierung

### ISSUE THREAD

**Issue by jan-christiansen** [beje8442/haskellToCoqCompiler#35]
Die Formatierung des Coq-Codes ist nicht sehr übersichtlich. Kann man den Pretty-Printer des Coq-Codes beeinflussen, um den code übersichtlicher zu formatieren?

**Comment by beje8442** [comment]
Für den ausgegebenen Code kann in der Funktion `renderPretty` ein `ribbonFrac` und `width` Wert zugewiesen werden. [(Dokumentation)](https://hackage.haskell.org/package/wl-pprint-text-1.2.0.0/docs/Text-PrettyPrint-Leijen-Text.html)
Außerdem habe ich manuell eine leere Zeile nach jeder Definition eingefügt.

**Comment by jan-christiansen** [comment]
Die Ausgabe sieht schon viel besser aus. Ich würde das Resultat gern beim nächsten Treffen noch mal kurz besprechen.

**Comment by beje8442** [comment]
Die falsche Klammerung von Variablen und Konstanten wurde behoben

**Comment by beje8442** [comment]
Die Fixpoint-Definitionen wurden im Pretty Printer vor dem `:=` umgebrochen und nicht-rekursive Funktionen nach dem `:=`.
Ich habe jetzt die Ausgabe aller Funktionen auf einen Zeilenumbruch hinter dem `:=` geändert
