### ISSUE TITLE
Stilverbesserungen

### ISSUE THREAD

**Issue by jan-christiansen** [beje8442/haskellToCoqCompiler#38]
Folgende Änderungen sollten am Code durchgeführt werden, um die Qualität zu verbessern.
* In einigen Funktionen wird unnötig Pattern-Matching betrieben. Zum Beispiel "matcht" die Funktion `convertMatchDef` auf die Liste `(p : ps)` baut sie aber in allen Fällen wieder zusammen.
* Es werden recht inkonsistent der Operator `$` und Klammerung verwendet. Besser ist es, immer explizite Klammerung zu verwenden.
* Es sollten alle Warnungen des Compilers behoben werden, die man mittels `Wall` bekommt.
* `compAndChangeArguments` looks like a `map`
* The definition of `convertArgumentsToTerms` looks odd.
* Please search for signatures like the signature of `unique` via hoogle.

**Comment by beje8442** [comment]
- Unnötiges Pattern-Matching `(p : ps)` wurde entfernt
- Der Operator `$` wurde entfernt
- Die Warnungen des Compilers wurden behoben
- `compAndChangeArguments` existiert nicht mehr
- Definition von `convertArgumentsToTerms` wurde verändert 
- `unique` wurde durch `nub` (`Data.List`) getauscht
