### ISSUE TITLE
"Plus"-Funktion von Haskell nach Coq übersetzen

### ISSUE THREAD

**Issue by beje8442** [beje8442/haskellToCoqCompiler#4]

**Comment by jan-christiansen** [comment]
Ein paar Anmerkungen zum Code

- bei der Definition von Funktionen Regeln verwenden statt case-Ausdrücke
- für alle Toplevel-Funktionen Typsignaturen angeben
- die Funktion `error :: String -> a` bei nicht implementierten Fällen verwenden

**Comment by jan-christiansen** [comment]
- der Haskell-AST sollte nicht direkt in einen String umgewandelt werden, sondern erst einmal in eine AST-Repräsentation von Coq
- wir verwenden einfach den Coq-AST und Pretty-Printer aus [hs-to-coq](https://github.com/antalsz/hs-to-coq)
- die Namen im AST orientieren sich an der [Sprachdefinition](https://coq.inria.fr/refman/language/gallina-specification-language.html?highlight=syntax#grammar-token-term)
- wir gehen davon aus, dass die Haskell-Beispiele nur Pattern Matching in Form von case-Ausdrücken verwenden und keine Regel-basierten Definitionen

**Comment by jan-christiansen** [comment]
Warum führt der generierte Code Pattern-Matching durch, obwohl die Original-Definition kein Pattern-Matching hat?
