### ISSUE TITLE
Testfälle hinzufügen

### ISSUE THREAD

**Issue by jan-christiansen** [beje8442/haskellToCoqCompiler#9]
Eine Datei sollte Testfälle enthalten, die einfach ausgeführt werden können. Zum Beispiel könnte man einfach einen Aufruf definieren, der eine Datei übersetzt, die alle Beispiele enthält, die bisher funktionieren.

**Comment by beje8442** [comment]
In der cabal-repl kann man nun mit dem Aufruf "test" eine Datei übersetzten, die Beispiele enthält, die funktionieren
